tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

brew "exa"
brew "fish"
brew "neovim"
brew "node"
brew "thefuck"
brew "wget"

cask "brave-browser"
cask "cleanmymac"
cask "iterm2"
cask "postman"
cask "slack"
cask "spotify"
cask "visual-studio-code"
